# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_active', 'InActive'), ('win', 'Win'), ('lose', 'Lose')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='signalbid',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_active', 'InActive'), ('win', 'Win'), ('lose', 'Lose')], max_length=20, verbose_name='Status'),
        ),
    ]
