# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20170107_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
