# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20170107_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='pair_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Currency Name'),
        ),
    ]
