# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170129_1755'),
        ('trade', '0004_currency_pair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now=True)),
                ('amount', models.FloatField(default=0.0, verbose_name='Bid amount')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.Profile')),
            ],
        ),
    ]
