# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170129_1755'),
        ('trade', '0005_userbalanceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trades', to='accounts.Profile')),
            ],
        ),
    ]
