# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170129_1755'),
        ('trade', '0006_autotrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('payout', models.CharField(max_length=100, verbose_name='Payout')),
                ('contract_id', models.CharField(max_length=500, verbose_name='contract_id')),
                ('longcode', models.CharField(max_length=5000, verbose_name='longcode')),
                ('buy_price', models.CharField(max_length=100, verbose_name='buy_price')),
                ('balance_after', models.CharField(max_length=100, verbose_name='balance_after')),
                ('shortcode', models.CharField(max_length=100, verbose_name='shortcode')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='transaction_id')),
                ('purchase_time', models.CharField(max_length=100, verbose_name='purchase_time')),
                ('start_time', models.CharField(max_length=100, verbose_name='start_time')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trade_histories', to='accounts.Profile')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trade_histories', to='trade.Signal')),
            ],
        ),
        migrations.AlterField(
            model_name='autotrade',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trades', to='accounts.Profile'),
        ),
    ]
