# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_errorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotradehistory',
            options={'default_permissions': ('add', 'change'), 'ordering': ['updated_at'], 'verbose_name': 'Auto Trade on User Account', 'verbose_name_plural': "Auto Trade's on User's Account"},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['updated_at'], 'verbose_name': 'Auto trade error Log', 'verbose_name_plural': 'Auto trading Erro Logs'},
        ),
        migrations.AlterModelOptions(
            name='userbalanceinfo',
            options={'ordering': ['updated_at'], 'verbose_name': 'User Balance table in every 24 hours', 'verbose_name_plural': "User's Balance table in every 24 hours"},
        ),
        migrations.AddField(
            model_name='errorlog',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlog',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
