# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.CharField(max_length=500, verbose_name='Body')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
