# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_id2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Broker account Id '),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Broker account Id '),
        ),
        migrations.AddField(
            model_name='profile',
            name='token2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Broker account Id '),
        ),
    ]
