# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170120_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Currency'),
        ),
    ]
