# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
