# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170129_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_error',
            field=models.CharField(choices=[(b'new', b'Need to Athenticate by binary.com for get trading working'), (b'expire', b'Token Expired, Please thenticate again'), (b'balance', b'Account having less balance, can not trade'), (b'deactivated', b'Your account deactivated on binary.com'), (b'real_account', b'Your Virtual account is Active only, need to activate real account and then authenticate again.'), (b'ok', b'Everything are Good, Enjoy trading with IqOptionExperts')], default=b'new', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[(b'real', b'Real Acount'), (b'virtual', b'Virtual account'), (b'new', b'Account not configured')], default=b'new', max_length=10),
        ),
    ]
